### ISSUE TITLE
Fix third party vulnerabilities identified by npm-audit

### ISSUE THREAD

**Issue by justinwb** [solid/solid-auth-oidc#13]
axle:solid-auth-oidc justin$ npm audit
...
found 16 vulnerabilities (15 low, 1 critical) in 5509 scanned packages
16 vulnerabilities require semver-major dependency updates.

**Comment by kjetilk** [comment]
> 16 vulnerabilities require semver-major dependency updates.

OMG, teh insanity!!!!!1111oneeleven

**Comment by kjetilk** [comment]
OK, I have updated this too. It turned out that these were all in `nyc` and `mocha`, and that limited the things that can go wrong in production, I suppose. But it is sure is scary...

@justinwb , the changes that you made for #12 , is that ready for release? If so, major, minor or patch?
