### ISSUE TITLE
loadClient method does not need to return a promise

### ISSUE THREAD

**Issue by dan-f** [solid/solid-auth-oidc#7]
https://github.com/solid/solid-auth-oidc/blob/master/src/index.js#L167-L191

**Comment by dmitrizagidulin** [comment]
The reason loadClient() returns a promise is because of [L187](https://github.com/solid/solid-auth-oidc/blob/master/src/index.js#L187) - `RelyingParty.from()` returns a promise. (And the reason for that is - re-hydrating keys from string into WebCrypto objects is an async operation.)

**Comment by dan-f** [comment]
I see.
